### PR TITLE
Zoom / pan the game area

### PR DESCRIPTION
**Pull request by gereleth**
hi #33

### CODE REVIEW

**Comment by eminence** [comment]
The pan itself feels great.  Surprisingly, I don't actually mind the fact that the normal on-click handler still runs.  It ends up being an interesting "shuffle" feature as I pan around 😄.  But sometimes my mouse happens to land on an edge zone and I end up inadvertently toggling an edge, which is problematic.

**Comment by gereleth** [comment]
I'm starting to like how these mouse controls work now.

Regular clicks rotate / lock tiles like before.

Edgemarks are now drawn with the mouse - click and drag along the border for a wall mark and across the border for a connection mark. Draw again to erase. I'm not getting random edgemarks from clicking too close to the border any more.

It's also now possible to lock multiple tiles by right-click and dragging over them.

I completely destroyed :bomb: touch support to get here so don't even try this on a phone. But I hope to build it back)).

**Comment by gereleth** [comment]
I think I fixed the touch interactions. There's now:

- tap tile to rotate
- tap and hold to start locking/unlocking. Once started you can lock multiple tiles by moving your finger around.
- draw a little line along the tile edge or across the tile edge to make an edge mark
- pinch to zoom, swipe with two fingers to pan
- pan with one finger once you move it a distance more than 1 tile width

I also made the puzzles start out zoomed in to a sane level rather than show a full puzzle.

Maybe this helps with #30. @ginabythebay could you maybe give the new controls a try at the [preview link](https://hexapipes-git-zoompan-gereleth.vercel.app/)?

**Comment by ginabythebay** [comment]
Wow this seems like quite an improvement to me! Thank you so much! I tried everything you listed and it all worked.  I did find drawing a line to be a bit finicky but at least now when I miss, tiles don’t start spinning so I m happy!

**Comment by gereleth** [comment]
Thanks for trying, I'm glad this all works. I have a couple more things to do and then I'll deploy the changes to the main site.

As currently implemented the edgemark gesture checks if there was some minimum distance traveled and if the middle point between touch start and touch end falls close enough to the middle of the edge. Maybe I'll tune what counts as "close enough" to make it less finicky.

**Comment by eminence** [comment]
This is looking great.  My only complaint is that the panning behavior can be a bit jarring, since you have to move the mouse a full tile before the pan will start.   I wonder if maybe a modifier key (maybe <kbd>shift</kbd>) could also be used to indicate an intent to pan (thus the pan could start immediately instead of waiting for a 1-tile minimum)

**Comment by gereleth** [comment]
That makes sense... Although if we're using keyboard at all we might go full WASD =). And rotate hovered tile with QE or something. And lock with space bar)).

**Comment by eminence** [comment]
Most of my games are played with one hand on WASD and another on a mouse, so this certainly would feel natural to me :)

**Pull request merged**
